spring.datasource.url=jdbc:mysql://localhost:3306/myauto?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=myauto_user
spring.datasource.password=your_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true